

#pragma once


#define ISM_PASSWDSUCCESS		100
#define ISM_CANCELADMISSION		101
#define ISM_USERCLOSED			102
#define ISM_USERCOUNT			103
#define ISM_TOTALUSERCOUNT		104
#define ISM_ACCOUNTEXPIRED      111
#define ISM_GAMETIMEOFTIMECARDUSER	112
#define ISM_CHECKTIMEACCOUNT    116

#define ISM_REQUEST_PUBLICKEY	117
#define ISM_SEND_PUBLICKEY		118
#define ISM_PREMIUMCHECK		119
#define ISM_EVENTCHECK			120
#define ISM_POTCASHLIST         121
#define ISM_POTCASHADD          122
#define ISM_POTCASHDEL          123

#define CM_QUERYCHR				100
#define CM_NEWCHR				101
#define CM_DELCHR				102
#define CM_SELCHR				103
#define CM_SELECTSERVER			104
#define CM_PROTOCOL				2000
#define CM_IDPASSWORD			2001
#define CM_ADDNEWUSER			2002
#define CM_CHANGEPASSWORD		2003
#define CM_UPDATEUSER			2004

#define SM_VERSION_AVAILABLE	500
#define SM_VERSION_FAIL			501
#define SM_PASSWD_FAIL			503
#define SM_CHGPASSWD_SUCCESS	506
#define SM_CHGPASSWD_FAIL		507
#define SM_STARTFAIL			526
#define SM_PASSOK_SELECTSERVER	529
#define SM_SELECTSERVER_OK		530
#define SM_NEEDUPDATE_ACCOUNT	531
#define SM_PASSOK_WRONGSSN		534
#define SM_NOT_IN_SERVICE		535
#define SM_SEND_PUBLICKEY		536
